(ts) fewer runtime globals (step 3)
PolymerLabs/arcs pull request #6869
Opened 2021-01-27 01:54 UTC by mmandlis

previous PRs by sjmiles@:
step 2: https://github.com/PolymerLabs/arcs/pull/6738
step 1: https://github.com/PolymerLabs/arcs/pull/6600

2021-01-27 02:26 UTC, mmandlis commented
dev-shell is operational, i'll fix web-shell in a follow up PR.

2021-02-01 04:41 UTC, shans approved these changes

2021-02-01 19:53 UTC, sjmiles requested changes
Great! Thank you so much.

2021-02-01 19:58 UTC, sjmiles approved these changes

2021-02-01 21:06 UTC, closed without merging